/*bjhbjkbkjbkjbljbljbjjn
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vp.fp;

import static com.vp.fp.FolderScanUtil.scanResultList;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author Lenovo
 */
public class designfolderNEW extends javax.swing.JFrame {

    /**
     * Creates new form designfolder
     */
    public designfolderNEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SAME = new javax.swing.JButton();
        DIFFERENCE = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Swap = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        Statistics = new javax.swing.JButton();
        Compare = new javax.swing.JButton();
        ALL = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Jfolder1name = new javax.swing.JFormattedTextField();
        Jfolder2name = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFolderbutton1 = new javax.swing.JButton();
        jFolderbutton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaScanResult = new javax.swing.JTextArea();
        jButtonScanAndCompare = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel = new javax.swing.JTabbedPane();
        jFILE1details = new javax.swing.JTabbedPane();
        jFILE2details = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jHomemenu = new javax.swing.JMenu();
        jFilemenu = new javax.swing.JMenu();
        jNewWindowMenuitem = new javax.swing.JMenuItem();
        jSearchMenu = new javax.swing.JMenu();
        jViewmenu = new javax.swing.JMenu();
        jToolsmenu = new javax.swing.JMenu();
        jReloadMenuitem = new javax.swing.JMenuItem();
        jHelpmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));

        SAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SAME.setForeground(new java.awt.Color(255, 0, 0));
        SAME.setText("=");
        SAME.setToolTipText("EQUAL");

        DIFFERENCE.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DIFFERENCE.setForeground(new java.awt.Color(0, 153, 51));
        DIFFERENCE.setText("-");
        DIFFERENCE.setToolTipText("DIFFERENCE");
        DIFFERENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIFFERENCEActionPerformed(evt);
            }
        });

        Next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Next.setText(">>");
        Next.setToolTipText("NEXT SEC");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Previous.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Previous.setText("<<");
        Previous.setToolTipText("PREV  SEC");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Swap.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Swap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\iconfinder_ic_swap_horiz_48px_352153.png")); // NOI18N
        Swap.setToolTipText("SWAP");
        Swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwapActionPerformed(evt);
            }
        });

        Reload.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Reload.setForeground(new java.awt.Color(255, 102, 0));
        Reload.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\iconfinder_icons_reload_1564525.png")); // NOI18N
        Reload.setToolTipText("RELOAD");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });

        Statistics.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Statistics.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\iconfinder_statistics_103716.png")); // NOI18N
        Statistics.setToolTipText("STATISTICS");
        Statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsActionPerformed(evt);
            }
        });

        Compare.setBackground(new java.awt.Color(255, 255, 255));
        Compare.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\audit (1).png")); // NOI18N
        Compare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompareActionPerformed(evt);
            }
        });

        ALL.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ALL.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\iconfinder_asterisk-small_6137904.png")); // NOI18N
        ALL.setToolTipText("ALL");
        ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ALL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DIFFERENCE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SAME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Previous)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Swap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reload, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Compare, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Compare, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(DIFFERENCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Previous, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Statistics)
                            .addComponent(Reload)
                            .addComponent(Swap))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ALL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\".\"", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("FILTERS:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Jfolder1name.setText("enter folder name here");
        Jfolder1name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jfolder1nameActionPerformed(evt);
            }
        });

        Jfolder2name.setText("enter folder name here");
        Jfolder2name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jfolder2nameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Folder 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Folder 2");

        jLabel4.setBackground(new java.awt.Color(51, 51, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Select Folders");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setBackground(new java.awt.Color(51, 51, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Statistics");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "File", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jFolderbutton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\folder.png")); // NOI18N
        jFolderbutton1.setText("Folder1");
        jFolderbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFolderbutton1ActionPerformed(evt);
            }
        });

        jFolderbutton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\New folder\\folder.png")); // NOI18N
        jFolderbutton2.setText("Folder2");
        jFolderbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFolderbutton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Jfolder2name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jfolder1name, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFolderbutton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFolderbutton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jfolder1name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFolderbutton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jfolder2name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFolderbutton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );

        jTextAreaScanResult.setColumns(20);
        jTextAreaScanResult.setRows(5);
        jScrollPane2.setViewportView(jTextAreaScanResult);
        jTextAreaScanResult.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jButtonScanAndCompare.setText("Scan And Compare");
        jButtonScanAndCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScanAndCompareActionPerformed(evt);
            }
        });

        jFILE1details.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel.addTab("FILE 1", jFILE1details);

        jFILE2details.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel.addTab("FILE 2", jFILE2details);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel)
        );

        jHomemenu.setText("Home");
        jMenuBar1.add(jHomemenu);

        jFilemenu.setText("File");

        jNewWindowMenuitem.setText("new window");
        jNewWindowMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewWindowMenuitemActionPerformed(evt);
            }
        });
        jFilemenu.add(jNewWindowMenuitem);

        jMenuBar1.add(jFilemenu);

        jSearchMenu.setText("Search");
        jMenuBar1.add(jSearchMenu);

        jViewmenu.setText("View");
        jMenuBar1.add(jViewmenu);

        jToolsmenu.setText("Tools");

        jReloadMenuitem.setText("Reload");
        jReloadMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReloadMenuitemActionPerformed(evt);
            }
        });
        jToolsmenu.add(jReloadMenuitem);

        jMenuBar1.add(jToolsmenu);

        jHelpmenu.setText("Help");
        jMenuBar1.add(jHelpmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(jButtonScanAndCompare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonScanAndCompare)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jReloadMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReloadMenuitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jReloadMenuitemActionPerformed

    private void jNewWindowMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewWindowMenuitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNewWindowMenuitemActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void DIFFERENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIFFERENCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DIFFERENCEActionPerformed

    private void Jfolder2nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jfolder2nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jfolder2nameActionPerformed

    private void Jfolder1nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jfolder1nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jfolder1nameActionPerformed

    private void ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALLActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousActionPerformed

    private void SwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwapActionPerformed

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReloadActionPerformed

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatisticsActionPerformed

    private void CompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompareActionPerformed

    private void jFolderbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFolderbutton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(this);
            if(option == JFileChooser.APPROVE_OPTION){
                       File file = fileChooser.getSelectedFile();
               System.out.println("Folder Selected: " + file.getName()+ file.getAbsolutePath());
               Jfolder1name.setText(file.getAbsolutePath());              
}
            else{
                System.out.println("Open command canceled");
               Jfolder1name.setText("Cancelled");
            }
    }//GEN-LAST:event_jFolderbutton1ActionPerformed

    private void jFolderbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFolderbutton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(this);
            if(option == JFileChooser.APPROVE_OPTION){
                       File file = fileChooser.getSelectedFile();
               System.out.println("Folder Selected: " + file.getName()+ file.getAbsolutePath());
               Jfolder2name.setText(file.getAbsolutePath());              
}
            else{
                System.out.println("Open command canceled");
               Jfolder2name.setText("Cancelled");
            }
    }//GEN-LAST:event_jFolderbutton2ActionPerformed

    private void jButtonScanAndCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScanAndCompareActionPerformed
        scanResultList.clear();
        FolderScanUtil.displayAllv2(new File(Jfolder1name.getText()));
        List<FileFolder> listScanFiles1 = new ArrayList<>(scanResultList);
        System.out.println(listScanFiles1);
        scanResultList.clear();
        FolderScanUtil.displayAllv2(new File(Jfolder2name.getText()));
        List<FileFolder> listScanFiles2 = new ArrayList<>(scanResultList);
        System.out.println(listScanFiles2);
        boolean scanResult = FolderScanUtil.compareFolders(listScanFiles1, listScanFiles2);
        jTextAreaScanResult.setText(String.valueOf(scanResult));
    }//GEN-LAST:event_jButtonScanAndCompareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(designfolderNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(designfolderNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(designfolderNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(designfolderNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new designfolderNEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL;
    private javax.swing.JButton Compare;
    private javax.swing.JButton DIFFERENCE;
    private javax.swing.JFormattedTextField Jfolder1name;
    private javax.swing.JFormattedTextField Jfolder2name;
    private javax.swing.JButton Next;
    private javax.swing.JButton Previous;
    private javax.swing.JButton Reload;
    private javax.swing.JButton SAME;
    private javax.swing.JButton Statistics;
    private javax.swing.JButton Swap;
    private javax.swing.JButton jButtonScanAndCompare;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTabbedPane jFILE1details;
    private javax.swing.JTabbedPane jFILE2details;
    private javax.swing.JMenu jFilemenu;
    private javax.swing.JButton jFolderbutton1;
    private javax.swing.JButton jFolderbutton2;
    private javax.swing.JMenu jHelpmenu;
    private javax.swing.JMenu jHomemenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jNewWindowMenuitem;
    private javax.swing.JTabbedPane jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem jReloadMenuitem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jSearchMenu;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaScanResult;
    private javax.swing.JMenu jToolsmenu;
    private javax.swing.JMenu jViewmenu;
    // End of variables declaration//GEN-END:variables
}
